### ISSUE TITLE
do we really need both test_mission_gen.py and gui.py?

### ISSUE THREAD

**Issue by rizar** [mila-udem/babyai#5]
We currently have two simple scripts to visualize BabyAI levels. Should we delete one of them?  Do we really need both of them? If we do need both of them, we should make their API consistent (right now `--env-name` in `gui.py` must be of the form `BabyAI-XXX-v0`, whereas `--level-name` in `test_mission_gen.py` must be just XXX).

**Comment by maximecb** [comment]
We've already had this discussion. I'd like to keep them both because the `gui` app use PyQT. It's a useful starting point if you want to create some UI with buttons and text boxes, but for those who have never coded it, the code will be a bit offputting. The `test_mission_gen` app is simpler, and it has a mode where you can see the partially observable view only I believe.

If we're going to unify argument naming... We use just "--env" in our training scripts, so we should support that in both. I'd like to maybe also keep `--level` in `test_mission_gen`, because the point was to do less typing, avoid needing the whole OpenAI id while testing things, but I guess it doesn't matter that much, we could use the OpenAI id for everything.

**Comment by rizar** [comment]
I see. My primary concern is that having inconsistent UI in the scripts
that people look at first is undesirable. Would you mind if I go ahead and
change make `test_mission_gen.py` to accept the full OpenAI id, and also to
create the environment by using OpenAI gym, and not directly?

**Comment by maximecb** [comment]
Sure, you can make that change, and also rename the arguments to just
"--env" like the other scripts.
